#!/bin/bash
# romanv automation script

./clean || exit

git checkout 4.14 || exit
git checkout HEAD -- boot || exit
##########################################
make partialclean -j || exit
### or
# make clean -j || exit
# ./configure CFLAGS="-Wno-strict-prototypes -Wno-unused-but-set-variable" || exit
##########################################
make world.opt -j || exit

git checkout constraints || exit
make coreall -j || exit
make bootstrap -j || exit
make -j || exit

./clean
