#!/bin/bash
# romanv automation script

make -j 7 || exit
make ocamlc || exit
make ocamlopt || exit

cd testsuite

make one TEST=tests/typing-misc/polyvars.ml

cd ..

# cat testsuite/_ocamltest/tests/typing-misc/polyvars/dump.txt
